### ISSUE TITLE
Result Reproduce

### ISSUE THREAD

**Issue by louisechen520** [microsoft/SeqSNN#10]
Hi, it is really an interesting work. I have a small question, I used the guidelines according to the description, however, for the metr_la datasets for example, I got the result of r^2: 0.5516, rse: 0.7066 for horizon 24. I was wondering if the hyperparameter was right, and if I need to adjust some of them instead of following the raw file in 'ispikformer_metr-la.yml'.

Thanks a lot.

**Comment by Lvchangze** [comment]
Thanks for your attention.
Something you can try:For the input data, we conduct a normalization. Please refer to SeqSNN/dataset/tsforecast.py Line 63. We use a "normalize" configuration to determine how we do normalization.
In exp/forecast/ispikformer/ispikformer_metr-la.yml Line 13, we use "normalize: 3".
Therefore, (1) if you want to use raw data to train your model, please use "normalize: 0" and "raw_label: True". However, the huge numbers may lead to bad prediction results because the threshold of spiking neurons defaults to 1. can change your

**Comment by Lvchangze** [comment]
Thanks for your attention.
Something you can try:
(1) For the input data, we conduct a normalization. Please refer to SeqSNN/dataset/tsforecast.py Line 63. We use a "normalize" configuration to determine how we do normalization.
In exp/forecast/ispikformer/ispikformer_metr-la.yml Line 13, we use "normalize: 3".
Therefore, you can try use "normalize: 0" or "1" or "2".
(2) Try more seeds, because the seed may influence the spilt of the datasets.
(3) Try more model architecture parameters like dim, d_ff, depths, and so on.
