### ISSUE TITLE
Prediction results

### ISSUE THREAD

**Issue by Lucas-cmd** [microsoft/SeqSNN#9]
I used the command "python -m SeqSNN.entry.tsforecast ./exp/forecast/ispikformer/ispikformer_metr-la.yml". But the values ​​of the forecast results I got are basically decimals, which does not correspond to the magnitude of the original data. I wonder if there are any parameters I need to pay attention to?

**Comment by Lvchangze** [comment]
Thanks for your attention.
For the input data, we conduct a normalization. Please refer to SeqSNN/dataset/tsforecast.py Line 63. We use a "normalize" configuration to determine how we do normalization.
In exp/forecast/ispikformer/ispikformer_metr-la.yml Line 13, we use "normalize: 3".
Therefore, (1) if you want to use raw data to train your model, please use "normalize: 0" and "raw_label: True". However, the huge numbers may lead to bad prediction results because the threshold of spiking neurons defaults to 1.
(2) if you choose to do a normalization to input data and want to get the same magnitude as the original data, you should conduct a "de-normalization" method, i.e.,  reversing how we do normalization. You can get the outputs and do this step by yourself.

**Comment by Lucas-cmd** [comment]
Thanks for your reply.
Could I ask again how to predict future values? Are there any hyperparameters that need to be set? Because I observed that the current prediction results are only within the given time period.

**Comment by Lvchangze** [comment]
Of course! I will take "exp/forecast/ispikformer/ispikformer_metr-la.yml" as an example. In this file, Line 11, "windows" indicates the length of the input time series. Line 12 "horizon" indicates the length of the predicted time series.
